---
- name: Add a ika user
  ansible.builtin.user:
    name: ika
    shell: /bin/bash

- name: Create ika directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "ika"
    group: "ika"
    mode: 0755
  loop:
    - /opt/ika/bin
    - /opt/ika/config
    - /opt/ika/db
    - /opt/ika/key-pairs

- name: Copy validator configuration file
  copy:
    src: "{{ node_config }}"
    dest: /opt/ika/config/validator.yaml
    owner: "ika"
    group: "ika"
    mode: 0644

- name: Copy genesis.blob
  copy:
    src: "{{ genesis_blob }}"
    dest: /opt/ika/config/genesis.blob
    owner: "ika"
    group: "ika"
    mode: 0644

- name: Copy protocol.key
  copy:
    src: "{{ keypair_path }}protocol.key"
    dest: /opt/ika/key-pairs/protocol.key
    owner: "ika"
    group: "ika"
    mode: 0600

- name: Copy network.key
  copy:
    src: "{{ keypair_path }}network.key"
    dest: /opt/ika/key-pairs/network.key
    owner: "ika"
    group: "ika"
    mode: 0600

- name: Copy worker.key
  copy:
    src: "{{ keypair_path }}worker.key"
    dest: /opt/ika/key-pairs/worker.key
    owner: "ika"
    group: "ika"
    mode: 0600

- name: Stop ika-node
  systemd:
    name: ika-node
    state: stopped
  ignore_errors: yes

- name: Remove authorities directory
  file:
    state: absent
    path: "/opt/ika/db/authorities_db"
  when: reset_db == true

- name: Remove consensus directory
  file:
    state: absent
    path: "/opt/ika/db/consensus_db"
  when: reset_db == true

- name: Place binary
  ansible.builtin.get_url:
    url: "https://releases.ika.io/{{ ika_release }}/ika-node"
    dest: /opt/ika/bin/ika-node
    force: true
    mode: "0755"

- name: Copy ika-node systemd service file
  copy:
    src: "../files/ika-node.service"
    dest: /etc/systemd/system/ika-node.service

- name: Reload ika-node systemd service file
  ansible.builtin.systemd:
    name: ika-node
    state: reloaded

- name: Start ika-node service
  systemd:
    name: ika-node
    state: started
  when: start_ika == true
