[package]
name = "pera-graphql-e2e-tests"
version = "0.1.0"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "End to end tests for Pera GraphQL"
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[lints]
workspace = true

[dev-dependencies]
datatest-stable.workspace = true
pera-graphql-rpc.workspace = true
pera-transactional-test-runner.workspace = true
tokio.workspace = true

[[test]]
name = "tests"
harness = false

[dependencies]

[features]
default = ["pg_backend"]
pg_integration = []
pg_backend = []

[target.'cfg(msim)'.dependencies]
msim.workspace = true
