[package]
name = "pera-graphql-config"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote.workspace = true
syn.workspace = true
