[package]
name = "ika-json-rpc-types"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
fastcrypto.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
colored.workspace = true
itertools.workspace = true
tracing.workspace = true
bcs.workspace = true
ika-protocol-config.workspace = true
ika-macros.workspace = true
ika-enum-compat-util.workspace = true
enum_dispatch.workspace = true
json_to_table.workspace = true
tabled.workspace = true

move-binary-format.workspace = true
move-core-types.workspace = true
move-bytecode-utils.workspace = true

mysten-metrics.workspace = true
ika-types.workspace = true
ika-json.workspace = true
ika-package-resolver.workspace = true

[dev-dependencies]
ika-types = { workspace = true, features = ["test-utils"] }

[features]
test-utils = []
