[package]
name = "ika-transactional-test-runner"
version = "0.1.0"
edition = "2021"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Move framework for Ika platform"
license = "Apache-2.0"
publish = false

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bcs.workspace = true
bimap.workspace = true
clap.workspace = true
eyre.workspace = true
once_cell.workspace = true
rand.workspace = true
regex.workspace = true
tempfile.workspace = true
async-trait.workspace = true
tokio.workspace = true
serde_json.workspace = true
futures.workspace = true
criterion.workspace = true

fastcrypto.workspace = true
move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-command-line-common.workspace = true
move-compiler.workspace = true
move-core-types.workspace = true
move-symbol-pool.workspace = true
move-transactional-test-runner.workspace = true
telemetry-subscribers.workspace = true

move-stdlib = { path = "../../external-crates/move/crates/move-stdlib" }
move-vm-runtime = { path = "../../external-crates/move/crates/move-vm-runtime" }

simulacrum.workspace = true
ika-graphql-rpc.workspace = true
ika-rest-api.workspace = true
ika-swarm-config.workspace = true
ika-config.workspace = true
ika-core = { workspace = true, features = ["test-utils"] }
ika-framework.workspace = true
ika-protocol-config.workspace = true
ika-types = { workspace = true, features = ["test-utils"]}
ika-json-rpc-types.workspace = true
ika-json-rpc.workspace = true
ika-json-rpc-api.workspace = true
ika-framework-snapshot.workspace = true
ika-storage.workspace = true
typed-store.workspace = true

[target.'cfg(msim)'.dependencies]
msim.workspace = true
