[package]
name = "simulacrum"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
async-trait.workspace = true   
anyhow.workspace = true
bcs.workspace = true
fastcrypto.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true
once_cell.workspace = true
rand.workspace = true
serde.workspace = true
tracing.workspace = true
prometheus.workspace = true
futures.workspace = true

move-bytecode-utils.workspace = true
shared-crypto.workspace = true
pera-config.workspace = true
pera-framework.workspace = true
pera-keys.workspace = true
pera-protocol-config.workspace = true
pera-storage.workspace = true
pera-types.workspace = true
pera-genesis-builder.workspace = true
pera-execution.workspace = true
pera-swarm-config.workspace = true
pera-transaction-checks.workspace = true
