[package]
name = "simulacrum"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
async-trait.workspace = true   
anyhow.workspace = true
bcs.workspace = true
fastcrypto.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true
once_cell.workspace = true
rand.workspace = true
serde.workspace = true
tracing.workspace = true
prometheus.workspace = true
futures.workspace = true

move-bytecode-utils.workspace = true
shared-crypto.workspace = true
ika-config.workspace = true
ika-framework.workspace = true
ika-keys.workspace = true
ika-protocol-config.workspace = true
ika-storage.workspace = true
ika-types.workspace = true
ika-genesis-builder.workspace = true
ika-execution.workspace = true
ika-swarm-config.workspace = true
ika-transaction-checks.workspace = true
