[package]
name = "IkaSystem"
version = "0.0.1"
published-at = "0x3"
edition = "2024.beta"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
Ika = { local = "../ika-framework" }

[addresses]
ika_system = "0x3"
