[package]
name = "pera-json"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
bcs.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true

pera-types.workspace = true

move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-core-types.workspace = true
fastcrypto = { workspace = true }

[dev-dependencies]
test-fuzz.workspace = true
pera-types = { workspace = true, features = ["test-utils"] }
pera-move-build.workspace = true
pera-framework.workspace = true
