[package]
name = "pera-light-client"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
name = "pera-light-client"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bcs.workspace = true
bytes.workspace = true
clap.workspace = true
move-core-types.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["full"] }
serde_yaml.workspace = true
serde_json.workspace = true
pera-types.workspace = true
pera-config.workspace = true
pera-rest-api.workspace = true
pera-json.workspace = true
pera-sdk.workspace = true
move-binary-format.workspace = true
pera-json-rpc-types.workspace = true
pera-package-resolver.workspace = true
