[package]
name = "pera-indexer-builder"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
tokio = { workspace = true, features = ["full"] }
async-trait.workspace = true
mysten-metrics.workspace = true
pera-types.workspace = true
pera-data-ingestion-core.workspace = true
tracing.workspace = true
prometheus.workspace = true
telemetry-subscribers.workspace = true