[package]
name = "ika-open-rpc"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lints]
workspace = true

[dependencies]
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
bcs.workspace = true
versions.workspace = true

[dev-dependencies]
anyhow.workspace = true
clap.workspace = true
pretty_assertions.workspace = true
tokio = { workspace = true, features = ["full"] }
fastcrypto.workspace = true
ika-json-rpc.workspace = true
ika-json-rpc-api.workspace = true
ika-json-rpc-types.workspace = true
ika-json.workspace = true
ika-types = { workspace = true, features = ["test-utils"] }
ika-protocol-config.workspace = true
rand.workspace = true

move-core-types.workspace = true

[[example]]
name = "generate-json-rpc-spec"
path = "src/generate_json_rpc_spec.rs"
test = false
