[package]
name = "pera-snapshot"
version = "0.1.0"
edition = "2021"
publish = false
license = "BSD-3-Clause-Clear"
authors = ["Mysten Labs <build@mystenlabs.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
integer-encoding.workspace = true
indicatif.workspace = true
anyhow.workspace = true
serde.workspace = true
bcs.workspace = true
byteorder.workspace = true
tracing.workspace = true
bytes.workspace = true
tokio-stream.workspace = true
num_enum.workspace = true
futures.workspace = true
object_store.workspace = true
prometheus.workspace = true
pera-types.workspace = true
pera-config.workspace = true
pera-core.workspace = true
pera-storage.workspace = true
pera-protocol-config.workspace = true
fastcrypto = { workspace = true, features = ["copy_key"] }
tokio = { workspace = true, features = ["full"] }
serde_json.workspace = true

[dev-dependencies]
tempfile.workspace = true
