[package]
name = "pera-authority-aggregation"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
pera-types.workspace = true
mysten-metrics.workspace = true
tokio.workspace = true
tracing.workspace = true
futures.workspace = true
