[package]
name = "ika-node"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lints]
workspace = true

[dependencies]
anemo.workspace = true
anemo-tower.workspace = true
arc-swap.workspace = true
axum.workspace = true
anyhow.workspace = true
base64.workspace = true
bcs.workspace = true
clap.workspace = true
consensus-core.workspace = true
prometheus.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
futures.workspace = true
parking_lot.workspace = true
tower.workspace = true
reqwest.workspace = true
tap.workspace = true
serde.workspace = true
bin-version.workspace = true
url.workspace = true
humantime.workspace = true

ika-archival.workspace = true
ika-tls.workspace = true
ika-macros.workspace = true
ika-config.workspace = true
ika-core.workspace = true
ika-rest-api.workspace = true
ika-storage.workspace = true
ika-network.workspace = true
ika-json-rpc.workspace = true
ika-json-rpc-api.workspace = true
ika-protocol-config.workspace = true
ika-snapshot.workspace = true
ika-telemetry.workspace = true
ika-types.workspace = true
mysten-metrics.workspace = true
mysten-service.workspace = true
mysten-common.workspace = true
narwhal-network.workspace = true
typed-store.workspace = true
mysten-network.workspace = true
telemetry-subscribers.workspace = true
fastcrypto.workspace = true
fastcrypto-zkp.workspace = true
move-vm-profiler.workspace = true

[target.'cfg(msim)'.dependencies]
ika-simulator.workspace = true
