[package]
name = "ika-json-rpc-tests"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lints]
workspace = true

[dependencies]

[dev-dependencies]
move-package.workspace = true
move-core-types.workspace = true
ika-config.workspace = true
ika-core.workspace = true
ika-keys.workspace = true
ika-move-build.workspace = true
ika-test-transaction-builder.workspace = true
ika-sdk.workspace = true
ika-macros.workspace = true
ika-simulator.workspace = true
ika-json.workspace = true
ika-json-rpc.workspace = true
ika-json-rpc-api.workspace = true
ika-json-rpc-types.workspace = true
ika-open-rpc.workspace = true
ika-open-rpc-macros.workspace = true
ika-protocol-config.workspace = true
ika-swarm-config.workspace = true
ika-types.workspace = true
test-cluster.workspace = true
telemetry-subscribers.workspace = true

anyhow.workspace = true
async-trait.workspace = true
bcs.workspace = true
hyper.workspace = true
jsonrpsee.workspace = true
prometheus.workspace = true
rand.workspace = true
reqwest.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true

