[package]
name = "pera-package-management"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[lib]
path = "src/lib.rs"

[dependencies]
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true

pera-json-rpc-types.workspace = true
pera-sdk.workspace = true
pera-types.workspace = true

move-core-types.workspace = true
move-package.workspace = true
move-symbol-pool.workspace = true
