[package]
name = "pera-transaction-checks"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
once_cell.workspace = true
pera-macros.workspace = true
pera-config.workspace = true
pera-protocol-config.workspace = true
pera-types.workspace = true
tracing.workspace = true
pera-execution.workspace = true
fastcrypto-zkp.workspace = true
