[package]
name = "ika"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[lints]
workspace = true

[dependencies]
anemo.workspace = true
anyhow.workspace = true
async-recursion.workspace = true
async-trait.workspace = true
axum.workspace = true
bcs.workspace = true
bin-version.workspace = true
bip32.workspace = true
camino.workspace = true
clap.workspace = true
codespan-reporting.workspace = true
datatest-stable.workspace = true
futures.workspace = true
http.workspace = true
im.workspace = true
inquire.workspace = true
insta.workspace = true
json_to_table.workspace = true
miette.workspace = true
num-bigint.workspace = true
prometheus.workspace = true
rand.workspace = true
regex.workspace = true
reqwest.workspace = true
rusoto_core.workspace = true
rusoto_kms.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
serde.workspace = true
shlex.workspace = true
signature.workspace = true
tabled.workspace = true
tap.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
uuid.workspace = true
url.workspace = true

ika-config.workspace = true
ika-bridge.workspace = true
ika-cluster-test.workspace = true
ika-execution = { path = "../../ika-execution" }
ika-faucet.workspace = true
ika-swarm-config.workspace = true
ika-graphql-rpc.workspace = true
ika-indexer.workspace = true
ika-genesis-builder.workspace = true
ika-types.workspace = true
ika-json.workspace = true
ika-swarm.workspace = true
ika-json-rpc-types.workspace = true
ika-sdk.workspace = true
ika-keys.workspace = true
ika-source-validation.workspace = true
ika-move = { workspace = true, features = ["all"] }
ika-move-build.workspace = true
ika-package-management.workspace = true
ika-protocol-config.workspace = true
shared-crypto.workspace = true
ika-replay.workspace = true
ika-transaction-builder.workspace = true
move-binary-format.workspace = true
move-bytecode-source-map.workspace = true
test-cluster.workspace = true

fastcrypto.workspace = true
fastcrypto-zkp.workspace = true

rustyline.workspace = true
rustyline-derive.workspace = true
colored.workspace = true
unescape.workspace = true
shell-words.workspace = true

tempfile.workspace = true
telemetry-subscribers.workspace = true

move-analyzer.workspace = true
move-bytecode-verifier-meter.workspace = true
move-core-types.workspace = true
move-package.workspace = true
move-compiler.workspace = true
csv.workspace = true
move-vm-profiler.workspace = true
move-vm-config.workspace = true
move-ir-types.workspace = true
move-command-line-common.workspace = true

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemalloc-ctl.workspace = true

[dev-dependencies]
prometheus.workspace = true
fs_extra.workspace = true
expect-test.workspace = true
assert_cmd.workspace = true
toml.workspace = true

test-cluster.workspace = true
ika-macros.workspace = true
ika-simulator.workspace = true
ika-test-transaction-builder.workspace = true
serde_json.workspace = true

[target.'cfg(msim)'.dependencies]
msim.workspace = true

[package.metadata.cargo-udeps.ignore]
normal = ["jemalloc-ctl"]

[[example]]
name = "generate-genesis-checkpoint"
path = "src/generate_genesis_checkpoint.rs"
test = false

[[test]]
name = "ptb_files_tests"
harness = false

[features]
tracing = [
    "ika-types/tracing",
    "ika-execution/tracing",
]
