[package]
name = "pera-swarm"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
rand.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["full"] }
futures.workspace = true
tempfile.workspace = true
tonic-health.workspace = true
tap.workspace = true
prometheus.workspace = true

pera-config.workspace = true
pera-swarm-config.workspace = true
pera-macros.workspace = true
pera-node.workspace = true
pera-protocol-config.workspace = true
pera-types.workspace = true
mysten-metrics.workspace = true
mysten-network.workspace = true
telemetry-subscribers.workspace = true

[target.'cfg(msim)'.dependencies]
pera-simulator.workspace = true

