[package]
name = "transaction-fuzzer"
version = "0.1.0"
edition = "2021"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Tool to fuzz the system with randomly generated transactions"
license = "Apache-2.0"
publish = false

[lints]
workspace = true

[dependencies]
proptest.workspace = true
proptest-derive.workspace = true
rand.workspace = true
move-core-types.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true

once_cell.workspace = true
ika-core.workspace = true
ika-protocol-config.workspace = true
ika-types = { workspace = true, features = ["fuzzing"] }
ika-move-build.workspace = true


[dev-dependencies]
ika-core = { workspace = true, features = ["test-utils"] }
ika-protocol-config.workspace = true
ika-types = { workspace = true, features = ["test-utils"] }
