[package]
name = "transaction-fuzzer"
version = "0.1.0"
edition = "2021"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Tool to fuzz the system with randomly generated transactions"
license = "BSD-3-Clause-Clear"
publish = false

[lints]
workspace = true

[dependencies]
proptest.workspace = true
proptest-derive.workspace = true
rand.workspace = true
move-core-types.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true

once_cell.workspace = true
pera-core.workspace = true
pera-protocol-config.workspace = true
pera-types = { workspace = true, features = ["fuzzing"] }
pera-move-build.workspace = true


[dev-dependencies]
pera-core = { workspace = true, features = ["test-utils"] }
pera-protocol-config.workspace = true
pera-types = { workspace = true, features = ["test-utils"] }
