[package]
name = "shared_no_tto"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Ika = { local = "../../../../crates/ika-framework/packages/ika-framework" }
common = { local = "../common" }

[addresses]
shared_no_tto = "0x0"
