[package]
name = "test-cluster"
authors = ["Mysten Labs <build@mystenlabs.com>"]
version = "0.1.0"
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bcs.workspace = true
fastcrypto.workspace = true
futures.workspace = true
tracing.workspace = true
jsonrpsee.workspace = true
tokio = { workspace = true, features = ["full", "tracing", "test-util"] }
rand.workspace = true
pera-config.workspace = true
pera-core = { workspace = true, features = ["test-utils"] }
pera-framework.workspace = true
pera-swarm-config.workspace = true
pera-json-rpc.workspace = true
pera-json-rpc-types.workspace = true
pera-json-rpc-api.workspace = true
pera-node.workspace = true
pera-protocol-config.workspace = true
pera-swarm.workspace = true
pera-types = { workspace = true, features = ["test-utils"] }
prometheus.workspace = true
pera-keys.workspace = true
pera-bridge.workspace = true
pera-sdk.workspace = true
pera-test-transaction-builder.workspace = true

move-binary-format.workspace = true

[target.'cfg(msim)'.dependencies]
pera-simulator.workspace = true
fastcrypto-zkp.workspace = true

[dev-dependencies]
pera-json-rpc-api.workspace = true
pera-macros.workspace = true
