[package]
name = "test-cluster"
authors = ["Mysten Labs <build@mystenlabs.com>"]
version = "0.1.0"
license = "Apache-2.0"
publish = false
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bcs.workspace = true
fastcrypto.workspace = true
futures.workspace = true
tracing.workspace = true
jsonrpsee.workspace = true
tokio = { workspace = true, features = ["full", "tracing", "test-util"] }
tokio-util.workspace = true
rand.workspace = true
tempfile.workspace = true
ika-config.workspace = true
ika-core = { workspace = true, features = ["test-utils"] }
ika-framework.workspace = true
ika-swarm-config.workspace = true
ika-indexer.workspace = true
ika-json-rpc.workspace = true
ika-json-rpc-types.workspace = true
ika-json-rpc-api.workspace = true
ika-node.workspace = true
ika-pg-temp-db.workspace = true
ika-protocol-config.workspace = true
ika-swarm.workspace = true
ika-types = { workspace = true, features = ["test-utils"] }
prometheus.workspace = true
ika-keys.workspace = true
ika-sdk.workspace = true
ika-test-transaction-builder.workspace = true

move-binary-format.workspace = true

[target.'cfg(msim)'.dependencies]
ika-simulator.workspace = true
fastcrypto-zkp.workspace = true

[dev-dependencies]
ika-json-rpc-api.workspace = true
ika-macros.workspace = true
