[package]
name = "pera-framework-tests"
version = "0.1.0"
edition = "2021"
authors = ["Mysten Labs <eng@mystenlabs.com>"]
description = "Runs Move tests for pera-framework"
license = "BSD-3-Clause-Clear"
publish = false

[lints]
workspace = true

[[test]]
name = "move_tests"
harness = false

[dev-dependencies]
datatest-stable.workspace = true
prometheus.workspace = true

pera-framework.workspace = true
pera-move = { workspace = true, features = ["unit_test"] }
pera-move-build.workspace = true
pera-protocol-config.workspace = true
pera-types.workspace = true

move-bytecode-verifier = { path = "../../external-crates/move/crates/move-bytecode-verifier" }
pera-adapter = { path = "../../pera-execution/latest/pera-adapter", package = "pera-adapter-latest" }
pera-verifier = { path = "../../pera-execution/latest/pera-verifier", package = "pera-verifier-latest" }

move-bytecode-verifier-meter.workspace = true
move-cli.workspace = true
move-package.workspace = true
move-unit-test.workspace = true

[dependencies]
