[package]
name = "pera-benchmark"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
anyhow = { workspace = true, features = ["backtrace"] }
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
itertools.workspace = true
tokio = { workspace = true, features = ["full"] }
strum.workspace = true
strum_macros.workspace = true
tracing.workspace = true
clap.workspace = true
prometheus.workspace = true
rand.workspace = true
indicatif.workspace = true
duration-str.workspace = true
hdrhistogram.workspace = true
comfy-table.workspace = true
bcs.workspace = true
tokio-util.workspace = true
pera-core.workspace = true
pera-config.workspace = true
pera-network.workspace = true
pera-storage.workspace = true
pera-types.workspace = true
pera-sdk.workspace = true
pera-keys.workspace = true
pera-json-rpc-types.workspace = true
pera-protocol-config.workspace = true
pera-test-transaction-builder.workspace = true
pera-swarm-config.workspace = true
pera-surfer.workspace = true
telemetry-subscribers.workspace = true
roaring.workspace = true
regex.workspace = true
fastcrypto-zkp.workspace = true

move-core-types.workspace = true
mysten-metrics.workspace = true
narwhal-node.workspace = true
test-cluster.workspace = true
sysinfo.workspace = true

[target.'cfg(msim)'.dependencies]
pera-framework.workspace = true
pera-framework-snapshot.workspace = true
pera-macros.workspace = true
pera-simulator.workspace = true
typed-store.workspace = true

[features]
benchmark = ["narwhal-node/benchmark"]
