[package]
name = "perans-indexer"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"
version.workspace = true

[dependencies]
diesel = { version = "2.1.4", features = ["postgres", "r2d2", "serde_json"] }
pera-data-ingestion-core.workspace = true
anyhow.workspace = true
async-trait.workspace = true
backoff.workspace = true
base64-url.workspace = true
bcs.workspace = true
bytes.workspace = true
futures.workspace = true
mysten-metrics.workspace = true
notify.workspace = true
object_store.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_yaml.workspace = true
prometheus.workspace = true
telemetry-subscribers.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
pera-storage.workspace = true
pera-types.workspace = true
url.workspace = true
pera-json-rpc.workspace = true
dotenvy = "0.15"
move-core-types.workspace = true
mysten-service.workspace = true

[dev-dependencies]
rand.workspace = true
tempfile.workspace = true
pera-types = { workspace = true, features = ["test-utils"] }
