[package]
name = "ika-indexer-alt"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[[bin]]
name = "ika-indexer-alt"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
backoff.workspace = true
bb8 = "0.8.5"
bcs.workspace = true
chrono.workspace = true
clap.workspace = true
const-str = { workspace = true, features = ["proc"] }
diesel = { workspace = true, features = ["chrono"] }
diesel-async = { workspace = true, features = ["bb8", "postgres", "async-connection-wrapper"] }
diesel_migrations.workspace = true
futures.workspace = true
itertools.workspace = true
prometheus.workspace = true
reqwest.workspace = true
serde.workspace = true
telemetry-subscribers.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
tokio-util.workspace = true
tracing.workspace = true
url.workspace = true

mysten-metrics.workspace = true
ika-field-count.workspace = true
ika-pg-temp-db.workspace = true
ika-protocol-config.workspace = true
ika-storage.workspace = true
ika-types.workspace = true

[dev-dependencies]
rand.workspace = true
tempfile.workspace = true
wiremock.workspace = true

ika-types = { workspace = true, features = ["test-utils"] }
