---
version: "3.9"
services:
  fullnode:
    # Note: Update the tag to the latest version of pera-io/pera-node for mainnet or testnet.
    image: pera-io/pera-node:mainnet-v1.19.1
    ports:
    - "8080:8080"
    - "8084:8084/udp"
    - "9000:9000"
    - "9184:9184"
    volumes:
    - ./fullnode-template.yaml:/opt/pera/config/fullnode.yaml:ro
    - ./genesis.blob:/opt/pera/config/genesis.blob:ro
    - ./peradb:/opt/pera/db:rw
    command: ["/opt/pera/bin/pera-node", "--config-path", "/opt/pera/config/fullnode.yaml"]
volumes:
  peradb:
