[package]
name = "pera-e2e-tests"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"
version.workspace = true

[lints]
workspace = true

[dependencies]

[dev-dependencies]
tempfile.workspace = true
futures.workspace = true
prometheus.workspace = true
fs_extra.workspace = true
indexmap.workspace = true
insta.workspace = true
jsonrpsee.workspace = true
test-cluster.workspace = true
rand.workspace = true
expect-test.workspace = true
tokio.workspace = true
tracing.workspace = true
assert_cmd.workspace = true
serde.workspace = true
bcs.workspace = true
anyhow.workspace = true
async-trait.workspace = true
clap.workspace = true
serde_json.workspace = true

move-binary-format.workspace = true
move-package.workspace = true
telemetry-subscribers.workspace = true
fastcrypto.workspace = true
fastcrypto-zkp.workspace = true
move-core-types.workspace = true

pera-bridge.workspace = true
pera-core.workspace = true
pera-framework.workspace = true
pera-json-rpc.workspace = true
pera-json-rpc-api.workspace = true
pera-node.workspace = true
pera-macros.workspace = true
pera-network.workspace = true
pera-simulator.workspace = true
pera-storage.workspace = true
mysten-metrics.workspace = true
pera-tool.workspace = true
pera-protocol-config.workspace = true
pera-types.workspace = true
pera-move-build.workspace = true
pera-swarm-config.workspace = true
pera-swarm.workspace = true
pera-test-transaction-builder.workspace = true
pera-config.workspace = true
pera-json-rpc-types.workspace = true
pera.workspace = true
pera-sdk.workspace = true
pera-keys.workspace = true
pera-rest-api.workspace = true
shared-crypto.workspace = true

passkey-types.workspace = true
passkey-client.workspace = true
passkey-authenticator.workspace = true
coset.workspace = true
url.workspace = true
p256.workspace = true
