[package]
name = "pera-node"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[lints]
workspace = true

[dependencies]
anemo.workspace = true
anemo-tower.workspace = true
arc-swap.workspace = true
axum.workspace = true
anyhow.workspace = true
base64.workspace = true
bcs.workspace = true
clap.workspace = true
prometheus.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
futures.workspace = true
parking_lot.workspace = true
tower.workspace = true
reqwest.workspace = true
tap.workspace = true
serde.workspace = true
snap.workspace = true
bin-version.workspace = true
url.workspace = true
humantime.workspace = true

pera-archival.workspace = true
pera-tls.workspace = true
pera-macros.workspace = true
pera-config.workspace = true
pera-core.workspace = true
pera-rest-api.workspace = true
pera-storage.workspace = true
pera-network.workspace = true
pera-json-rpc.workspace = true
pera-json-rpc-api.workspace = true
pera-protocol-config.workspace = true
pera-snapshot.workspace = true
pera-telemetry.workspace = true
pera-types.workspace = true
mysten-metrics.workspace = true
mysten-service.workspace = true
mysten-common.workspace = true
narwhal-network.workspace = true
narwhal-worker.workspace = true
typed-store.workspace = true
mysten-network.workspace = true
telemetry-subscribers.workspace = true
fastcrypto.workspace = true
fastcrypto-zkp.workspace = true
move-vm-profiler.workspace = true

[target.'cfg(msim)'.dependencies]
pera-simulator.workspace = true
