[package]
name = "bls_signature"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Ika = { local = "../../../../crates/ika-framework/packages/ika-framework" }

[addresses]
bls_signature = "0x0"
