[package]
name = "pera-json-rpc-api"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
jsonrpsee.workspace = true
once_cell.workspace = true
prometheus.workspace = true
tap.workspace = true
tracing.workspace = true
fastcrypto.workspace = true
mysten-metrics.workspace = true
pera-json.workspace = true
pera-json-rpc-types.workspace = true
pera-open-rpc.workspace = true
pera-open-rpc-macros.workspace = true
pera-types.workspace = true

# NOTE: It's important to keep the above dependency list short.
# This and the pera-sdk crate are widely used to develop on Pera and it's valuable
# to not have to pull in the entire pera repo for it.

[dev-dependencies]
