[package]
name = "ika-surfer"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
ika-core.workspace = true
ika-swarm-config.workspace = true
ika-json-rpc-types.workspace = true
ika-move-build.workspace = true
ika-protocol-config.workspace = true
ika-types.workspace = true
test-cluster.workspace = true

async-trait.workspace = true
bcs.workspace = true
clap.workspace = true
futures.workspace = true
indexmap.workspace = true
rand.workspace = true
tokio = { workspace = true, features = ["full", "tracing", "test-util"] }
tracing.workspace = true

move-binary-format.workspace = true
move-core-types.workspace = true
telemetry-subscribers.workspace = true

[dev-dependencies]
prometheus.workspace = true
ika-macros.workspace = true
ika-simulator.workspace = true

move-package.workspace = true
