[package]
name = "pera-move"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
clap.workspace = true
colored.workspace = true
once_cell = { workspace = true, optional = true }
serde_json.workspace = true
serde_yaml.workspace = true
tracing.workspace = true
prometheus.workspace = true
bin-version.workspace = true

move-binary-format.workspace = true
move-cli.workspace = true
move-compiler.workspace = true
move-disassembler.workspace = true
move-ir-types.workspace = true
move-package.workspace = true
move-prover.workspace = true
move-unit-test.workspace = true
telemetry-subscribers.workspace = true
tokio = { workspace = true, features = ["full"] }

move-vm-runtime = { path = "../../external-crates/move/crates/move-vm-runtime" }
pera-move-natives = { path = "../../pera-execution/latest/pera-move-natives", package = "pera-move-natives-latest" }

pera-move-build.workspace = true
pera-protocol-config.workspace = true
pera-types.workspace = true
better_any = "0.1.1"

[target.'cfg(not(target_env = "msvc"))'.dependencies]
jemalloc-ctl.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
futures.workspace = true
jsonrpsee.workspace = true
rand.workspace = true
tempfile.workspace = true

move-package.workspace = true

mysten-metrics.workspace = true
pera-core.workspace = true
pera-macros.workspace = true
pera-node.workspace = true
pera-simulator.workspace = true

[package.metadata.cargo-udeps.ignore]
normal = ["jemalloc-ctl"]

[features]
default = []
build = []
coverage = []
disassemble = []
prove = []
unit_test = ["build", "dep:once_cell"]
calibrate = []
all = ["build", "coverage", "disassemble", "prove", "unit_test", "calibrate"]
