[package]
name = "counter"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Pera = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/pera-framework/packages/pera-framework", rev = "framework/devnet" }

[addresses]
counter = "0x0"
