[package]
name = "pera-move-lsp"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
tokio = { workspace = true, features = ["full"] }

bin-version.workspace = true
move-analyzer.workspace = true

