[package]
name = "regulated-token"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Pera = { local = "../../crates/pera-framework/packages/pera-framework" }

[addresses]
regulated_token = "0x0"
