[package]
name = "ika-json-rpc-api"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
jsonrpsee.workspace = true
once_cell.workspace = true
prometheus.workspace = true
tap.workspace = true
tracing.workspace = true
fastcrypto.workspace = true
mysten-metrics.workspace = true
ika-json.workspace = true
ika-json-rpc-types.workspace = true
ika-open-rpc.workspace = true
ika-open-rpc-macros.workspace = true
ika-types.workspace = true

# NOTE: It's important to keep the above dependency list short.
# This and the ika-sdk crate are widely used to develop on Ika and it's valuable
# to not have to pull in the entire ika repo for it.

[dev-dependencies]
