[package]
name = "pera-rpc-loadgen"
version.workspace = true
edition = "2021"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
clap.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
serde.workspace = true
tonic.workspace = true
futures.workspace = true
dirs.workspace = true
dashmap.workspace = true
itertools.workspace = true

shellexpand.workspace = true

pera-types = { workspace = true, features = ["test-utils"]}
pera-keys.workspace = true
pera-sdk.workspace = true
telemetry-subscribers.workspace = true
pera-json-rpc.workspace = true
pera-json-rpc-types.workspace = true
strum.workspace = true
shared-crypto.workspace = true
serde_json.workspace = true
strum_macros.workspace = true

[dev-dependencies]
test-cluster.workspace = true


[[bin]]
name = "pera-rpc-loadgen"
path = "src/main.rs"
