[package]
name = "BridgedKa"
version = "0.0.1"
edition = "legacy"

[dependencies]
MoveStdlib = { local = "../../../../../crates/ika-framework/packages/move-stdlib" }
Ika = { local = "../../../../../crates/ika-framework/packages/ika-framework" }

[addresses]
bridged_ka = "0x0"
