[package]
name = "pera-test-transaction-builder"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
bcs.workspace = true

shared-crypto.workspace = true
pera-genesis-builder.workspace = true
pera-move-build.workspace = true
pera-sdk.workspace = true
pera-types.workspace = true

move-core-types.workspace = true
