[package]
name = "pera-surfer"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
pera-core.workspace = true
pera-swarm-config.workspace = true
pera-json-rpc-types.workspace = true
pera-move-build.workspace = true
pera-protocol-config.workspace = true
pera-types.workspace = true
test-cluster.workspace = true

async-trait.workspace = true
bcs.workspace = true
clap.workspace = true
futures.workspace = true
indexmap.workspace = true
rand.workspace = true
tokio = { workspace = true, features = ["full", "tracing", "test-util"] }
tracing.workspace = true

move-binary-format.workspace = true
move-core-types.workspace = true
telemetry-subscribers.workspace = true

[dev-dependencies]
prometheus.workspace = true
pera-macros.workspace = true
pera-simulator.workspace = true

move-package.workspace = true
