[package]
name = "ika-mvr-indexer"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
rand = "0.8.5"
async-trait.workspace = true
axum.workspace = true
backoff.workspace = true
bb8 = "0.8.5"
bcs.workspace = true
bytes.workspace = true
chrono.workspace = true
clap = { workspace = true, features = ["env"] }
csv.workspace = true
diesel = { workspace = true, features = ["chrono", "serde_json"] }
diesel-async = { workspace = true, features = ["bb8", "postgres", "async-connection-wrapper"] }
futures.workspace = true
hex.workspace = true
indicatif.workspace = true
itertools.workspace = true
jsonrpsee.workspace = true
object_store.workspace = true
prometheus.workspace = true
rayon.workspace = true
regex.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
strum.workspace = true
strum_macros.workspace = true
tap.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["rt"] }
toml.workspace = true
tracing.workspace = true
url.workspace = true

fastcrypto = { workspace = true, features = ["copy_key"] }
mysten-metrics.workspace = true
simulacrum.workspace = true
ika-config.workspace = true
ika-archival.workspace = true
ika-core.workspace = true
ika-data-ingestion-core.workspace = true
ika-json.workspace = true
ika-json-rpc.workspace = true
ika-json-rpc-api.workspace = true
ika-json-rpc-types.workspace = true
ika-open-rpc.workspace = true
ika-sdk.workspace = true
ika-snapshot.workspace = true
ika-storage.workspace = true
ika-types.workspace = true
ika-package-resolver.workspace = true
ika-protocol-config.workspace = true
telemetry-subscribers.workspace = true
ika-rest-api.workspace = true
ika-transaction-builder.workspace = true
ika-synthetic-ingestion.workspace = true

move-core-types.workspace = true
move-bytecode-utils.workspace = true
move-binary-format.workspace = true

diesel_migrations.workspace = true
cached.workspace = true
tokio-stream.workspace = true
dashmap.workspace = true

[dev-dependencies]
ika-keys.workspace = true
ika-move-build.workspace = true
ika-swarm-config.workspace = true
ika-test-transaction-builder.workspace = true
test-cluster.workspace = true
ntest.workspace = true
criterion.workspace = true

[[bin]]
name = "ika-mvr-indexer"
path = "src/main.rs"
