[package]
name = "BridgedBTC"
version = "0.0.1"
edition = "legacy"

[dependencies]
MoveStdlib = { local = "../../../../crates/pera-framework/packages/move-stdlib" }
Pera = { local = "../../../../crates/pera-framework/packages/pera-framework" }

[addresses]
bridged_btc = "0x0"
