[package]
name = "move-abstract-interpreter-v2"
version = "0.1.0"
authors = ["The Move Contributors"]
description = "Move abstract interpreter"
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
move-binary-format.workspace = true

[features]
default = []
