[package]
name = "pera-replay"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
bcs.workspace = true
prometheus.workspace = true
async-trait.workspace = true
jsonrpsee.workspace = true
async-recursion.workspace = true
clap = { version = "4.1.4", features = ["derive"] }
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
similar.workspace = true
thiserror.workspace = true
tracing.workspace = true
rand.workspace = true
lru.workspace = true
parking_lot.workspace = true
serde_with.workspace = true
serde_yaml.workspace = true
shellexpand.workspace = true
tempfile.workspace = true
http.workspace = true

move-vm-config.workspace = true
move-binary-format.workspace = true
move-bytecode-utils.workspace = true
move-core-types.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tabled.workspace = true
regex.workspace = true

shared-crypto.workspace = true
pera-config.workspace = true
pera-core.workspace = true
pera-execution.workspace = true
pera-framework.workspace = true
pera-json-rpc.workspace = true
pera-json-rpc-api.workspace = true
pera-json-rpc-types.workspace = true
pera-protocol-config.workspace = true
pera-sdk.workspace = true
pera-storage.workspace = true
pera-transaction-checks.workspace = true
pera-types.workspace = true
