[package]
name = "pera-json-rpc-tests"
version = "0.0.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[lints]
workspace = true

[dependencies]

[dev-dependencies]
move-package.workspace = true
move-core-types.workspace = true
pera-config.workspace = true
pera-core.workspace = true
pera-keys.workspace = true
pera-move-build.workspace = true
pera-test-transaction-builder.workspace = true
pera-sdk.workspace = true
pera-macros.workspace = true
pera-simulator.workspace = true
pera-json.workspace = true
pera-json-rpc.workspace = true
pera-json-rpc-api.workspace = true
pera-json-rpc-types.workspace = true
pera-open-rpc.workspace = true
pera-open-rpc-macros.workspace = true
pera-protocol-config.workspace = true
pera-swarm-config.workspace = true
pera-types.workspace = true
test-cluster.workspace = true
telemetry-subscribers.workspace = true

anyhow.workspace = true
async-trait.workspace = true
bcs.workspace = true
hyper.workspace = true
jsonrpsee.workspace = true
prometheus.workspace = true
rand.workspace = true
reqwest.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true

