[package]
name = "pera-tool"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
num_cpus.workspace = true
bcs.workspace = true
clap = { version = "4.1.4", features = ["derive"] }
colored.workspace = true
comfy-table.workspace = true
eyre.workspace = true
futures.workspace = true
hex.workspace = true
move-core-types.workspace = true
itertools.workspace = true
ron.workspace = true
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
strum_macros.workspace = true
tempfile.workspace = true
tracing.workspace = true
prometheus.workspace = true
object_store.workspace = true
indicatif.workspace = true

anemo-cli.workspace = true
anemo.workspace = true
telemetry-subscribers.workspace = true
tokio = { workspace = true, features = ["full"] }
typed-store.workspace = true
fastcrypto.workspace = true

narwhal-storage.workspace = true
narwhal-types.workspace = true
pera-config.workspace = true
pera-core.workspace = true
pera-network.workspace = true
pera-snapshot.workspace = true
pera-protocol-config.workspace = true
pera-replay.workspace = true
pera-sdk.workspace = true
pera-storage.workspace = true
pera-types.workspace = true
pera-archival.workspace = true
pera-package-dump.workspace = true
bin-version.workspace = true
