[package]
name = "reviews_rating"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
Ika = { local = "../../../crates/ika-framework/packages/ika-framework", override = true }

[addresses]
reviews_rating =  "0x0"
