[package]
name = "pera-indexer"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
axum.workspace = true
backoff.workspace = true
bcs.workspace = true
chrono.workspace = true
serde_with.workspace = true
clap.workspace = true
tap.workspace = true
diesel = { workspace = true, optional = true }
diesel-derive-enum = { workspace = true, optional = true }
futures.workspace = true
itertools.workspace = true
jsonrpsee.workspace = true
prometheus.workspace = true
serde.workspace = true
serde_json.workspace = true
rayon.workspace = true
regex.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tracing.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-util = { workspace = true, features = ["rt"] }
url.workspace = true

fastcrypto = { workspace = true, features = ["copy_key"] }
mysten-metrics.workspace = true
pera-data-ingestion-core.workspace = true
pera-json.workspace = true
pera-json-rpc.workspace = true
pera-json-rpc-api.workspace = true
pera-json-rpc-types.workspace = true
pera-open-rpc.workspace = true
pera-sdk.workspace = true
pera-types.workspace = true
pera-package-resolver.workspace = true
pera-protocol-config.workspace = true
telemetry-subscribers.workspace = true
pera-rest-api.workspace = true
pera-transaction-builder.workspace = true

move-core-types.workspace = true
move-bytecode-utils.workspace = true
move-binary-format.workspace = true

diesel_migrations.workspace = true
cached.workspace = true
secrecy = "0.8.0"
downcast = "0.11.0"

[features]
pg_integration = []
default = ["postgres-feature"]
postgres-feature = ["diesel/postgres", "diesel/postgres_backend", "diesel-derive-enum/postgres"]
mysql-feature = ["diesel/mysql", "diesel/mysql_backend", "diesel-derive-enum/mysql"]

[dev-dependencies]
pera-keys.workspace = true
pera-move-build.workspace = true
pera-test-transaction-builder.workspace = true
test-cluster.workspace = true
ntest.workspace = true
criterion.workspace = true
simulacrum.workspace = true

[[bin]]
name = "pera-indexer"
path = "src/main.rs"
