[package]
name = "pera-cluster-test"
version.workspace = true
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
futures.workspace = true
serde_json.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["full"] }
jsonrpsee.workspace = true
tracing.workspace = true
clap.workspace = true
diesel.workspace = true
reqwest.workspace = true
async-trait.workspace = true
anyhow = { workspace = true, features = ["backtrace"] }
uuid.workspace = true
prometheus.workspace = true
fastcrypto.workspace = true
shared-crypto.workspace = true
derivative.workspace = true
regex.workspace = true

pera-indexer.workspace = true
pera-faucet.workspace = true
pera-graphql-rpc.workspace = true
pera-swarm.workspace = true
pera-swarm-config.workspace = true
pera-json-rpc-types.workspace = true
pera-sdk.workspace = true
pera-keys.workspace = true
pera-types.workspace = true
pera-core.workspace = true
pera-json.workspace = true
pera-config.workspace = true
pera-test-transaction-builder.workspace = true
telemetry-subscribers.workspace = true

test-cluster.workspace = true
move-core-types.workspace = true

[features]
default = ["postgres-feature"]
postgres-feature = ["diesel/postgres", "diesel/postgres_backend"]
pg_integration = []
