[package]
name = "pera-package-resolver"
version = "0.1.0"
edition = "2021"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait.workspace = true
bcs.workspace = true
move-binary-format.workspace = true
move-core-types.workspace = true
# TODO: `move-command-line-common` is used for `ErrorBitset`. We should
# refactor the crate into a `move-utils` at some point and use that instead
# here once we do.
move-command-line-common.workspace = true
pera-types.workspace = true
thiserror.workspace = true
pera-rest-api.workspace = true
tokio.workspace = true
eyre.workspace = true
serde.workspace = true
lru.workspace = true

[dev-dependencies]
hyper.workspace = true
insta.workspace = true
move-compiler.workspace = true
serde_json.workspace = true
pera-move-build.workspace = true
tower.workspace = true
