[package]
name = "PeraSystem"
version = "0.0.1"
published-at = "0x3"
edition = "2024.beta"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
Pera = { local = "../pera-framework" }

[addresses]
pera_system = "0x3"
