[package]
name = "pera-cost"
version = "0.1.0"
authors = ["Mysten Labs <build@mystenlabs.com>"]
license = "BSD-3-Clause-Clear"
publish = false
edition = "2021"

[dependencies]
pera-types.workspace = true
anyhow.workspace = true
tokio = { workspace = true, features = ["full"] }
serde.workspace = true
strum.workspace = true
strum_macros.workspace = true
bcs.workspace = true

[dev-dependencies]
insta.workspace = true
test-cluster.workspace = true
pera-config.workspace = true
pera-swarm-config.workspace = true
pera-test-transaction-builder.workspace = true
pera-move-build.workspace = true
move-cli.workspace = true
move-disassembler.workspace = true
pera-json-rpc-types.workspace = true
